### ISSUE TITLE
Refactoring plan

### ISSUE THREAD

**Issue by juaram2** [juaram2/JobPlanetAndroid#1]
# Description

## 0. Clean Architecture
> 코드 전체적으로 의존성을 띄고 있음.
> 클린 아키텍쳐를 목표로 리팩토링 해야한다.

## 1. ViewHolder
> View 대신 Binding

```kt
open class DefaultViewHolder(private val binding: Binding) : RecyclerView.ViewHolder(binding.root)
```

## 2. Adapter
> findViewById(R.id.xx) 대신 binding.xx

```kt
class CellListAdapter(private val listener: CellListChildAdapterListener) : RecyclerView.Adapter<DefaultViewHolder>() {
  ..
  class CompanyTypeViewHolder(view: View) : DefaultViewHolder(view) {
    val logo: ImageView = binding.logo
    ..
  }
  ..
}
```

## 3. interface
> 디테일 화면과 검색 api 추가
> Add getRecruitDetail(id: String)
> Add searchItems(searchTerm: String)

```kt
interface JobPlanetApi {
    @GET("/mobile-config/test_data_recruit_items.json")
    suspend fun getRecruitItems(): Response<RecruitItemsModel>

    @GET("/mobile-config/test_data_cell_items.json")
    suspend fun getCellItems(): Response<CellItemsModel>

    @GET("/mobile-config/test_data_recruit_items.json")
    suspend fun searchRecruitDetail(id: String): Response<RecruitItemModel>

    @GET("/mobile-config/test_data_recruit_items.json")
    suspend fun searchRecruitItems(searchTerm: String): Response<RecruitItemsModel>

    @GET("/mobile-config/test_data_cell_items.json")
    suspend fun searchCellItems(searchTerm: String): Response<CellItemsModel>
}
```

## 4. ViewModel
> api 추상화
> 일반 목록과 검색 목록 get 함수 분리
> Change calling Api 
> Add searchItems(searchTerm: String)

```kt
class CellVM(private val api: JobPlanetApi, application: Application): BaseVM(application) {
  ..
  fun getCellItems() {
    ..
  }

  fun searchCellItems(searchTerm: String) {
    _loading.postValue(true)
      viewModelScope.launch(Dispatchers.Main) {
        val response = api.searchCellItems(searchTerm)
        try {
          ..
          response.body()?.let { data ->
            _cells.value.addAll(data)
          }
        } catch (e: Exception) {
          ..
        }
      }
    }
  }
}
```

# Additional Context

* _Including pseudocode_
* UI도 좋지만, _아키텍쳐_ 에 더 집중. 과거 UI 관련 업무를 했던 터라 1dp 틀어진 것을 참지 못하고 시간을 많이 할애했다.

**Comment by juaram2** [comment]
## Task
- [x] BindingAdapter
- [x] Create ViewHolder according to cell_type
- [x] Fix ordering rating number
- [ ] Fix disappearing horizontal view
- [ ] Fix UI aligned center and wrap_content
- [ ] Fix missing tab position when search
